import { clientsClaim } from 'workbox-core';
import { createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';
import { offlineFallback, staticResourceCache } from 'workbox-recipes';

clientsClaim();

/**
 * We are not wrapping it in a 'message' event as per the new update.
 * @see https://developers.google.com/web/tools/workbox/modules/workbox-core
 */
self.skipWaiting();

/**
 * Precache all of the assets generated by your build process.
 * Their URLs are injected into the manifest variable below.
 * This variable must be present somewhere in your service worker file,
 * even if you decide not to use precaching. @see https://cra.link/PWA
 */
precacheAndRoute(self.__WB_MANIFEST);

/**
 * @see https://developer.chrome.com/docs/workbox/modules/workbox-strategies/#stale-while-revalidate
 * @see https://developer.chrome.com/docs/workbox/modules/workbox-strategies/#network-first-network-falling-back-to-cache
 */
registerRoute(
  /.*/,
  // new StaleWhileRevalidate({
  new NetworkFirst({
    cacheName: 'static-resources',
  })
);

/**
 * @see https://developer.chrome.com/docs/workbox/reference/workbox-recipes/
 */
offlineFallback({
  pageFallback: '/index.html',
});
