# Quelle: https://de.overleaf.com/learn/how-to/Why_do_I_keep_getting_the_compile_timeout_error_message%3F
# Hilft, wenn das Projekt nicht aufhört zu kompilieren, bis der Timeout kommt, ohne, dass der mögliche Fehler angezeigt werden.
# Datei 'latexmkrc' ohne Extensions/Dateiendung im Hauptverzeichnis anlegen. Das Kompilieren stoppt beim ersten Fehler und zeigt diesen an.
#   aktiv im Projekt verwenden => Dateiname muss lauten: latexmkrc
#   inaktiv im Projekt belassen => Datei umbenennen, z.b. in: tmp_latexmkrc

$pdflatex = 'pdflatex --halt-on-error %O %S';
$lualatex = 'lualatex --halt-on-error %O %S';
$xelatex = 'xelatex --halt-on-error %O %S';
$latex = 'latex --halt-on-error %O %S';