import { clientsClaim } from 'workbox-core';
import { createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { setDefaultHandler, registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

clientsClaim();

/**
 * We are not wrapping it in a 'message' event as per the new update.
 * @see https://developers.google.com/web/tools/workbox/modules/workbox-core
 */
self.skipWaiting();

/**
 * Precache all of the assets generated by your build process.
 * Their URLs are injected into the manifest variable below.
 * This variable must be present somewhere in your service worker file,
 * even if you decide not to use precaching. @see https://cra.link/PWA
 */
precacheAndRoute(self.__WB_MANIFEST);

/** 
 * @see https://developers.google.com/web/tools/workbox/guides/common-recipes#cache_css_and_javascript_files 
 */
registerRoute(
  ({request}) => 
    request.destination === 'script' ||
    request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
  })
);

/**
 * Route all other requests to the root index.html 
 * @see https://developer.chrome.com/docs/workbox/modules/workbox-routing/#set-a-default-handler
 */ 
setDefaultHandler(createHandlerBoundToURL('/index.html'));
